---
language: node_js
node_js:
  - '4'
  - '6.11.0'
  - 'stable'

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm
    - node_modules

env:
  - EMBER_TRY_SCENARIO=ember-lts-2.12
  - EMBER_TRY_SCENARIO=ember-default

matrix:
  fast_finish: true
  allow_failures:
    - node_js: 'stable'

stages:
  - name: after_success
    # only want to deploy if master build
    if: branch = master

branches:
  only:
    - master

before_install:
  - npm config set spin false
  - chmod +x deploy.sh

script:
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO --skip-cleanup

after_success:
    - ./deploy.sh
