---
language: node_js
node_js:
  - '6.11.0'
  - 'stable'

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm
    - node_modules

env:
  - EMBER_TRY_SCENARIO=ember-lts-2.12
  - EMBER_TRY_SCENARIO=ember-default

matrix:
  fast_finish: true
  allow_failures:
    - node_js: 'stable'

before_install:
  - npm config set spin false
  - npm install -g pr-bumper@^2.0.0

install:
  - $(npm root -g)/pr-bumper/.travis/maybe-install.sh

before_script:
  - $(npm root -g)/pr-bumper/.travis/maybe-check-scope.sh

script:
  - $(npm root -g)/pr-bumper/.travis/maybe-test.sh
  - $(npm root -g)/pr-bumper/.travis/maybe-bump-version.sh

after_success:
  - $(npm root -g)/pr-bumper/.travis/maybe-publish-coverage.sh
  - $(npm root -g)/pr-bumper/.travis/maybe-publish-gh-pages.sh

deploy:
  on:
    all_branches: true
    node: '6.11.0'
    tags: true
